### ISSUE TITLE
Navigator Refactor for 4.0

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/morningstar#1021]
In GitLab by @ghost on May 6, 2022, 17:25

## Navigator refactor
One of the many things that need to be worked on. Most composers aren't used at all, they are overriden. This needs to also be fixed.

### Searches
1. [ ] Remove usage of navigator_filter and hardcode the search queries to minimize issues. These aren't needed in database in any single way as they never change.

2. [ ] If search results empty, error message. More info #506 

3. [ ] My own room search (properly implemented :rolling_eyes: ) More info #586 

#### Composer Usage (currently hardcoded stuff)
1. MyRoomRightsSearchMessageComposer
2. MyRoomsSearchMessageComposer (this is where errors also are)
3. MyRoomHistorySearchMessageComposer

### Navigator Publics
1. [ ] Navigator publics are sorted the same way popular rooms are. This is not intended, they are supposed to be hardcoded by order number. More info #483 

2. [ ] is_public = '1' shouldn't trigger a category automatically. This breaks the structure. Is public should only override room owners name.

### Room stuff
1. [ ] If room is_public = '1', you shouldn't get a doorbell upon entering room If you're owner. More info #737 
2. Unique tag names.

these need to be double-checked tbh

### Moderation
1. [ ] Wordfilters applied and checked when user edits room settings and/or creates a room.

more to be added tbh
