### ISSUE TITLE
Navigator massthread (Navigator, 09/03)

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/morningstar#994]
In GitLab by @ghost on Mar 9, 2022, 16:17

## Navigator massthread
So this is a massthread about issues related to navigator as of right now (9.3.2022).

## Missing features/enhancements
- [x] Navigator order_number for public rooms ( #764 )
- [ ] Own room-tab search ( #586 )
- [ ] No text If search results return empty ( #506 )

## Bugs/issues
- [x] Navigator search sometimes case sensitive. Easier to locate If room name has for example # ( #938 )
- [ ] Navigator defaults to top rooms upon room delete ( #211 )
- [ ] Invisible rooms in "my friends" without rights ( #824 )

**Comment by brenoepics** [comment]
In GitLab by @ghost on Mar 23, 2022, 19:30

marked the checklist item **Navigator search sometimes case sensitive. Easier to locate If room name has for example # ( #938 )** as completed

**Comment by brenoepics** [comment]
In GitLab by @ghost on Apr 10, 2022, 18:58

marked the checklist item **Navigator order_number for public rooms ( #764 )** as completed
