### ISSUE TITLE
Moderation massthread (09/03)

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/morningstar#995]
In GitLab by @ghost on Mar 9, 2022, 16:33

## Massthread of Moderation
A massthread for improving moderation on retros.

## Missing features/enhancements
- [ ] Add mute alert ( #798 )
- [ ] Mute for IP | possibly for mac? ( #992 )
- [ ] Filter for all areas + room chat ( #830 )
- [ ] Rank-specific chat bubble restrictions ( #674 )
- [ ] Request room guides ( #54 )

## Bugs
- [ ] Help ticket issue w/ room reports and such ( #794 )
- [ ] Machineban + superban fix ( #748 & #749 )
- [ ] Ipban doesn't ban the user ( #750 )
- [ ] Chatlog doesn't show the specific rooms chatlog ( #505 )
- [ ] When wordfilter IS hidden/report, the message doesn't trigger anything else defined ( #971 )
