### ISSUE TITLE
Pets massthread (09/03)

### ISSUE THREAD

**Issue by brenoepics** [brenoepics/morningstar#996]
In GitLab by @ghost on Mar 9, 2022, 16:45

## Massthread of Pets
Pets have to be re-done in order for most of these to get fixed, but yeah.
If you are a developer and wish to look at these, dragons are defined in default + I can offer you some specific pet thingies.

## Missing features/enhancements
- [ ] Rare pets ( #628 )
- [ ] Pet toys ( #12 )
- [ ] Pet nests ( #553 )
- [ ] Pet eating, drinking ( #548 )
- [x] Pet basic commands (
- [ ] Pet scratch should walk you ( #939 )
- [ ] Cow boxes ( #19 )
- [ ] Monsterplant rarities ( #544 )

## Bugs
- [ ] Pet breeding, subtasks ( #650 )
- [ ] Horse default color ( #479 )
- [ ] Monsterplant achievements ( #929 )
- [x] Pet follows ( #545 )
- [x] Pet pickup ( #654 )

**Comment by brenoepics** [comment]
In GitLab by @Harmonic on Apr 7, 2022, 18:52

marked the checklist item **Pet basic commands (** as completed

**Comment by brenoepics** [comment]
In GitLab by @ghost on Apr 8, 2022, 19:26

marked the checklist item **Pet pickup ( #654 )** as completed

**Comment by brenoepics** [comment]
In GitLab by @ghost on Apr 8, 2022, 19:26

marked the checklist item **Pet follows ( #545 )** as completed
